name: FreeBSD

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - triple: x86_64-unknown-freebsd
            dockcross: freebsd-x64
            cargo_args:

          - triple: aarch64-unknown-freebsd
            dockcross: freebsd-arm64
            cargo_args: -Z build-std

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          docker run --rm -v $(pwd):/work -e BUILDER_UID=$(id -u) -e BUILDER_GID=$(id -g) -e BUILDER_USER=$(id -un) -e BUILDER_GROUP=$(id -gn) ghcr.io/cynix/dockcross-${{ matrix.target.dockcross }} env CARGO_PROFILE_RELEASE_STRIP=true cargo build --release ${{ matrix.target.cargo_args }}
          tar -C target/${{ matrix.target.triple }}/release/ -zcf akr-${GITHUB_SHA::7}-${{ matrix.target.triple }}.tar.gz --numeric-owner --owner=0 --group=0 ./akr

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: tarballs
          path: akr-*.tar.gz

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: tarballs

      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: edge
          prerelease: true
          files: akr-*.tar.gz
